apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-script
  namespace: backups
data:
  backup.sh: |
    #!/bin/bash
    set -e
    
    # Install zip utility
    apt-get update -qq > /dev/null 2>&1
    apt-get install -y zip > /dev/null 2>&1
    
    # Configuration
    TIMESTAMP=$(date +%Y%m%d_%H%M%S)
    BACKUP_DIR="/backups"
    DB_HOST="postgresql.postgresql.svc.cluster.local"
    DB_PORT="5432"
    DB_USER="odoo"
    DB_NAME="postgres"
    ODOO_DATA_DIR="/odoo-data"
    RETENTION_DAYS=7
    
    # Get Odoo version from environment variable (default to 17.0 if not set)
    ODOO_VERSION=${ODOO_VERSION:-17.0}
    ODOO_MAJOR=$(echo $ODOO_VERSION | cut -d'.' -f1)
    ODOO_MINOR=$(echo $ODOO_VERSION | cut -d'.' -f2)
    
    echo "ðŸ”„ Starting COMPLETE backup at $(date)"
    echo "================================================"
    
    # 1. Backup all Odoo databases individually
    echo "ðŸ“¦ [1/1] Backing up Odoo databases..."
    
    # Get list of Odoo databases (exclude postgres, template0, template1)
    DATABASES=$(PGPASSWORD=${POSTGRES_PASSWORD} psql \
      -h ${DB_HOST} \
      -p ${DB_PORT} \
      -U ${DB_USER} \
      -d postgres \
      -t -c "SELECT datname FROM pg_database WHERE datname NOT IN ('postgres', 'template0', 'template1');" | grep -v '^$')
    
    if [ -z "$DATABASES" ]; then
        echo "   âš ï¸  No Odoo databases found to backup"
    else
        for DB in $DATABASES; do
            DB_CLEAN=$(echo $DB | xargs)  # Remove whitespace
            echo "   ðŸ“¦ Backing up database: ${DB_CLEAN}..."
            
            # Create temporary directory for this database
            TEMP_DIR="${BACKUP_DIR}/temp_${DB_CLEAN}_${TIMESTAMP}"
            mkdir -p ${TEMP_DIR}
            
            # 1. Backup database in PostgreSQL custom format (for pg_restore)
            echo "      ðŸ“¦ Creating PostgreSQL dump..."
            PGPASSWORD=${POSTGRES_PASSWORD} pg_dump \
              -h ${DB_HOST} \
              -p ${DB_PORT} \
              -U ${DB_USER} \
              -d ${DB_CLEAN} \
              -F c \
              -f ${TEMP_DIR}/database.dump
            
            DUMP_SIZE=$(du -h ${TEMP_DIR}/database.dump | cut -f1)
            echo "         âœ… PostgreSQL dump: ${DUMP_SIZE}"
            
            # 2. Backup database in SQL format (for Odoo restore)
            echo "      ðŸ“„ Creating SQL dump (Odoo compatible)..."
            PGPASSWORD=${POSTGRES_PASSWORD} pg_dump \
              -h ${DB_HOST} \
              -p ${DB_PORT} \
              -U ${DB_USER} \
              -d ${DB_CLEAN} \
              --no-owner \
              --no-privileges \
              -f ${TEMP_DIR}/dump.sql
            
            SQL_SIZE=$(du -h ${TEMP_DIR}/dump.sql | cut -f1)
            echo "         âœ… SQL dump: ${SQL_SIZE}"
            
            # Backup filestore for this database (if exists)
            if [ -d "${ODOO_DATA_DIR}/filestore/${DB_CLEAN}" ]; then
                echo "      ðŸ“ Backing up filestore..."
                tar -czf ${TEMP_DIR}/filestore.tar.gz \
                  -C ${ODOO_DATA_DIR}/filestore ${DB_CLEAN}/
                FS_SIZE=$(du -h ${TEMP_DIR}/filestore.tar.gz | cut -f1)
                echo "         âœ… Filestore: ${FS_SIZE}"
            fi
            
            # Create manifest for this database
            echo "Backup Date: $(date)" > ${TEMP_DIR}/manifest.txt
            echo "Timestamp: ${TIMESTAMP}" >> ${TEMP_DIR}/manifest.txt
            echo "Database: ${DB_CLEAN}" >> ${TEMP_DIR}/manifest.txt
            echo "Odoo Version: ${ODOO_VERSION}" >> ${TEMP_DIR}/manifest.txt
            echo "PostgreSQL Version: 17" >> ${TEMP_DIR}/manifest.txt
            
            # Create directory for this database
            mkdir -p ${BACKUP_DIR}/${DB_CLEAN}
            
            # Create PostgreSQL backup (tar.gz with database.dump)
            echo "      ðŸ“¦ Creating PostgreSQL backup..."
            cd ${BACKUP_DIR}
            tar -czf ${DB_CLEAN}/${TIMESTAMP}_postgresql.tar.gz -C ${TEMP_DIR} database.dump filestore.tar.gz manifest.txt 2>/dev/null || \
            tar -czf ${DB_CLEAN}/${TIMESTAMP}_postgresql.tar.gz -C ${TEMP_DIR} database.dump manifest.txt
            
            PG_SIZE=$(du -h ${DB_CLEAN}/${TIMESTAMP}_postgresql.tar.gz | cut -f1)
            echo "         âœ… ${TIMESTAMP}_postgresql.tar.gz (${PG_SIZE})"
            
            # Create Odoo-compatible backup (zip with dump.sql)
            echo "      ðŸ“¦ Creating Odoo-compatible backup..."
            
            # Create Odoo backup directory structure
            ODOO_BACKUP_DIR="${TEMP_DIR}/odoo_backup_${TIMESTAMP}"
            mkdir -p ${ODOO_BACKUP_DIR}
            
            # Copy dump.sql
            cp ${TEMP_DIR}/dump.sql ${ODOO_BACKUP_DIR}/
            
            # Create manifest.json (Odoo-compatible format)
            echo "{" > ${ODOO_BACKUP_DIR}/manifest.json
            echo "    \"odoo_dump\": \"1\"," >> ${ODOO_BACKUP_DIR}/manifest.json
            echo "    \"db_name\": \"${DB_CLEAN}\"," >> ${ODOO_BACKUP_DIR}/manifest.json
            echo "    \"version\": \"${ODOO_VERSION}-$(date +%Y%m%d)\"," >> ${ODOO_BACKUP_DIR}/manifest.json
            echo "    \"version_info\": [${ODOO_MAJOR}, ${ODOO_MINOR}, 0, \"final\", 0, \"\"]," >> ${ODOO_BACKUP_DIR}/manifest.json
            echo "    \"major_version\": \"${ODOO_VERSION}\"," >> ${ODOO_BACKUP_DIR}/manifest.json
            echo "    \"pg_version\": \"17.0\"" >> ${ODOO_BACKUP_DIR}/manifest.json
            echo "}" >> ${ODOO_BACKUP_DIR}/manifest.json
            
            # Extract and copy filestore if exists
            if [ -f "${TEMP_DIR}/filestore.tar.gz" ]; then
                mkdir -p ${ODOO_BACKUP_DIR}/filestore
                tar -xzf ${TEMP_DIR}/filestore.tar.gz -C ${ODOO_BACKUP_DIR}/filestore --strip-components=1
            fi
            
            # Create ZIP with files in root (not in subdirectory)
            cd ${ODOO_BACKUP_DIR}
            zip -r ${BACKUP_DIR}/${DB_CLEAN}/${TIMESTAMP}_odoo.zip . > /dev/null 2>&1
            cd ${TEMP_DIR}
            rm -rf ${ODOO_BACKUP_DIR}
            
            ODOO_SIZE=$(du -h ${BACKUP_DIR}/${DB_CLEAN}/${TIMESTAMP}_odoo.zip | cut -f1)
            echo "         âœ… ${TIMESTAMP}_odoo.zip (${ODOO_SIZE})"
            
            # Cleanup temp directory
            rm -rf ${TEMP_DIR}
        done
    fi
    
    echo ""
    echo "âœ… Backup process completed!"
    echo "   $(echo $DATABASES | wc -w) database(s) backed up"
    
    # Clean old backups
    echo ""
    echo "ðŸ§¹ Cleaning backups older than ${RETENTION_DAYS} days..."
    find ${BACKUP_DIR} -name "*.tar.gz" -type f -mtime +${RETENTION_DAYS} -delete
    find ${BACKUP_DIR} -name "*.zip" -type f -mtime +${RETENTION_DAYS} -delete
    
    # List current backups
    echo ""
    echo "ðŸ“‹ Current backups by database:"
    for DB_DIR in ${BACKUP_DIR}/*/; do
        if [ -d "$DB_DIR" ]; then
            DB_NAME=$(basename "$DB_DIR")
            echo "  ðŸ“ ${DB_NAME}:"
            ls -lh ${DB_DIR}*_postgresql.tar.gz 2>/dev/null | awk '{print "     ðŸ˜ " $9 " (" $5 ")"}'
            ls -lh ${DB_DIR}*_odoo.zip 2>/dev/null | awk '{print "     ðŸ“¦ " $9 " (" $5 ")"}'
        fi
    done
    
    echo ""
    echo "âœ… Backup process completed at $(date)"
    echo "================================================"
