apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-data-pv-0
  labels:
    type: postgresql-db
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "manual"
  hostPath:
    path: /var/lib/odoo-storage/postgres
    type: DirectoryOrCreate
