apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-data
  namespace: odoo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "manual"
  resources:
    requests:
      storage: 10Gi
  volumeName: odoo-data-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-extra-addons
  namespace: odoo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "manual"
  resources:
    requests:
      storage: 5Gi
  volumeName: odoo-extra-addons-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-oca-addons
  namespace: odoo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "manual"
  resources:
    requests:
      storage: 10Gi
  volumeName: odoo-oca-addons-pv
